version: "3.8"

services:

  # 1. Frontend Service (React + Nginx)
  oscar-yolo-client:
    build: 
      context: ./client
    image: oscar066/oscar-yolo-client:v1.1.0
    container_name: oscar-yolo-client
    ports:
      # Exposes the Nginx server on port 80.
      - "80:80"
    networks:
      - app-net
    depends_on:
      - oscar-yolo-backend

  # 2. Backend Service (Node.js API)
  oscar-yolo-backend:
    build:
      context: ./backend
    image: oscar066/oscar-yolo-backend:v1.1.0
    container_name: oscar-yolo-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://app-ip-mongo:27017/yolomy
    networks:
      - app-net
    depends_on:
      - app-ip-mongo

  # 3. Database Service (MongoDB)
  app-ip-mongo:
    image: mongo:noble
    container_name: app-mongo
    ports:
      - "27017:27017"
    networks:
      - app-net
    volumes:
      # Persists database data on the host machine
      - app-mongo-data:/data/db

# Creates the private network for services to communicate
networks:
  app-net:
    driver: bridge

# Creates the volume on the host for persistent data storage
volumes:
  app-mongo-data: