# This file contains all the tasks for the 'docker-setup' role.
# The goal is to install Docker and Docker Compose on the Ubuntu VM

---
# Task 1: Install prerequisite packages for adding a new repository over HTTPS.
- name: Install prerequisite packages for Docker repository
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
    

# Task 2: Create the directory to hold the GPG key.
- name: Create directory for Docker GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'


# Task 3: Add Docker's official GPG key to ensure package authenticity.
- name: Add Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0644'
    force: yes


# Task 4: Set up the official Docker APT repository.
- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker


# Task 5: Install Docker Engine, CLI, and the Docker Compose plugin.
- name: Install Docker Engine and Docker Compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes 


# Task 6: Add the 'vagrant' user to the 'docker' group.
- name: Add vagrant user to the docker group
  user:
    name: vagrant
    groups: docker
    append: yes



# Task 7: Install Python PIP, which is needed to install the Docker SDK for Python.
- name: Install python3-pip
  apt:
    name: python3-pip
    state: present



# Task 8: Install the Docker SDK for Python.
- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present